/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChoreUpdateRequestDto {
  dbStatus?: boolean;
  description?: string | null;
  estimatedDuration?: number | null;
  finishedOn?: string | null;
  id?: number;
  productionStationId?: number;
  productionStationMemberId?: number;
  productionTaskId?: number;
  rowVersion?: string | null;
  scheduledTo?: string;
  startedOn?: string | null;
  statusId?: number;
  taskTypeId?: number;
  title?: string | null;
}
