/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChoreAddRequestDto {
  description?: string | null;
  estimatedDuration?: number | null;
  finishedOn?: string | null;
  productionStationId?: number;
  productionStationMemberId?: number;
  productionTaskId?: number;
  scheduledTo?: string;
  startedOn?: string | null;
  statusId?: number;
  taskTypeId?: number;
  title?: string | null;
}
