/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrganizationUpdateRequestDto {
  dbStatus?: boolean;
  description?: string | null;
  id?: number;
  location?: string | null;
  name?: string | null;
  ownerId?: number;
  rowVersion?: string | null;
}
