/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrganizationMemberUpdateRequestDto {
  dbStatus?: boolean;
  id?: number;
  organizationId?: number;
  roleId?: number;
  rowVersion?: string | null;
  userId?: number;
}
