/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrganizationAddRequestDto {
  description?: string | null;
  location?: string | null;
  name?: string | null;
  ownerId?: number | null;
}
