/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductionStationUpdateRequestDto {
  dbStatus?: boolean;
  description?: string | null;
  id?: number;
  name?: string | null;
  organizationId?: number;
  rowVersion?: string | null;
}
