/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductionStationAddRequestDto {
  description?: string | null;
  name?: string | null;
  organizationId?: number | null;
}
