/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductionStationMemberUpdateRequestDto {
  dbStatus?: boolean;
  id?: number;
  organizationMemberId?: number;
  productionStationId?: number;
  rowVersion?: string | null;
}
