/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductionTaskUpdateRequestDto {
  createdById?: number;
  dbStatus?: boolean;
  id?: number;
  priorityId?: number;
  rowVersion?: string | null;
}
