/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskTypeUpdateRequestDto {
  dbStatus?: boolean;
  id?: number;
  name?: string | null;
  rowVersion?: string | null;
}
