/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserUpdateRequestDto {
  dbStatus?: boolean;
  email?: string | null;
  fullName?: string | null;
  id?: number;
  latestLogin?: string | null;
  rowVersion?: string | null;
  username?: string | null;
}
