/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ProductionTaskGetAllGet$Params {

/**
 * Count
 */
  count?: boolean;

/**
 * Filter
 */
  filter?: string;

/**
 * OrderBy
 */
  orderby?: string;

/**
 * Skip
 */
  skip?: string;

/**
 * Top
 */
  top: string;
}

export function productionTaskGetAllGet(http: HttpClient, rootUrl: string, params: ProductionTaskGetAllGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, productionTaskGetAllGet.PATH, 'get');
  if (params) {
    rb.query('count', params.count, {});
    rb.query('filter', params.filter, {});
    rb.query('orderby', params.orderby, {});
    rb.query('skip', params.skip, {});
    rb.query('top', params.top, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

productionTaskGetAllGet.PATH = '/ProductionTask/GetAll';
